### ISSUE TITLE
[BUG] Komori Chiyu should be the FLATTEST

### ISSUE THREAD

**Issue by NiaMori** [sannaha/bigwatermelon#1]
Komori Chiyu is `AA` while Enfer Mirei is `AB`.

The correct order should be 古守血遊 -> 暗妃鲁咪蕾.

This is a critical bug and it should be fixed as soon as possible since it seriously hurt the feelings of oniku.

**Comment by Octomouch** [comment]
草

**Comment by LonelyPrime** [comment]
yes yes yes
